//! Pre-defined check library based on tech press benchmarking methodologies
//!
//! Sources:
//! - GamersNexus testing methodology
//! - Tom's Hardware testing methodology
//! - LTT Labs MarkBench
//! - Back2Gaming Windows tweaks guide

use crate::config::{CheckConfig, CheckType};

/// Categories for organizing checks in the library UI
pub const CATEGORIES: &[&str] = &[
    "Power Settings",
    "Windows Gaming Features",
    "Performance Registry Tweaks",
    "Background Apps",
    "RGB/Peripheral Software",
    "Monitoring Software",
    "Laptop-Specific",
];

/// A pre-defined check from the library
#[derive(Clone)]
pub struct LibraryCheck {
    pub id: &'static str,
    pub name: &'static str,
    pub category: &'static str,
    pub description: &'static str,
    pub check_type: CheckType,
    pub registry_path: Option<&'static str>,
    pub registry_key: Option<&'static str>,
    pub process_name: Option<&'static str>,
    pub expected_value: Option<&'static str>,
    pub laptop_only: bool,
}

impl LibraryCheck {
    /// Convert to a CheckConfig for adding to a scenario
    pub fn to_check_config(&self) -> CheckConfig {
        CheckConfig {
            id: self.id.to_string(),
            name: self.name.to_string(),
            check_type: self.check_type.clone(),
            enabled: true,
            registry_path: self.registry_path.map(|s| s.to_string()),
            registry_key: self.registry_key.map(|s| s.to_string()),
            process_name: self.process_name.map(|s| s.to_string()),
            expected_value: self.expected_value.map(|s| s.to_string()),
        }
    }
}

/// Get all checks in the library
pub fn get_library() -> Vec<LibraryCheck> {
    vec![
        // ===== Power Settings =====
        LibraryCheck {
            id: "power_high_performance",
            name: "High Performance Power Plan",
            category: "Power Settings",
            description: "Required for consistent benchmark results (GamersNexus)",
            check_type: CheckType::PowerScheme,
            registry_path: None,
            registry_key: None,
            process_name: None,
            expected_value: Some("high_performance"),
            laptop_only: false,
        },
        LibraryCheck {
            id: "power_ultimate",
            name: "Ultimate Performance Power Plan",
            category: "Power Settings",
            description: "Maximum performance, may need to be enabled via PowerShell",
            check_type: CheckType::PowerScheme,
            registry_path: None,
            registry_key: None,
            process_name: None,
            expected_value: Some("ultimate_performance"),
            laptop_only: false,
        },
        LibraryCheck {
            id: "power_balanced",
            name: "Balanced Power Plan",
            category: "Power Settings",
            description: "Default Windows power plan, good for productivity testing",
            check_type: CheckType::PowerScheme,
            registry_path: None,
            registry_key: None,
            process_name: None,
            expected_value: Some("balanced"),
            laptop_only: false,
        },
        // Power Mode (Windows slider)
        LibraryCheck {
            id: "power_mode_best",
            name: "Power Mode: Best Performance",
            category: "Power Settings",
            description: "Windows power slider set to maximum performance",
            check_type: CheckType::PowerMode,
            registry_path: None,
            registry_key: None,
            process_name: None,
            expected_value: Some("best_performance"),
            laptop_only: false,
        },
        LibraryCheck {
            id: "power_mode_better",
            name: "Power Mode: Better Performance",
            category: "Power Settings",
            description: "Windows power slider set to better performance",
            check_type: CheckType::PowerMode,
            registry_path: None,
            registry_key: None,
            process_name: None,
            expected_value: Some("better_performance"),
            laptop_only: false,
        },
        LibraryCheck {
            id: "power_mode_balanced",
            name: "Power Mode: Balanced",
            category: "Power Settings",
            description: "Windows power slider set to balanced (default)",
            check_type: CheckType::PowerMode,
            registry_path: None,
            registry_key: None,
            process_name: None,
            expected_value: Some("balanced"),
            laptop_only: false,
        },

        // ===== Windows Gaming Features =====
        LibraryCheck {
            id: "game_mode_enabled",
            name: "Game Mode Enabled",
            category: "Windows Gaming Features",
            description: "Prioritizes game processes and reduces background activity",
            check_type: CheckType::RegistryDword,
            registry_path: Some("HKCU\\Software\\Microsoft\\GameBar"),
            registry_key: Some("AutoGameModeEnabled"),
            process_name: None,
            expected_value: Some("1"),
            laptop_only: false,
        },
        LibraryCheck {
            id: "game_mode_disabled",
            name: "Game Mode Disabled",
            category: "Windows Gaming Features",
            description: "For benchmarks that prefer Game Mode off",
            check_type: CheckType::RegistryDword,
            registry_path: Some("HKCU\\Software\\Microsoft\\GameBar"),
            registry_key: Some("AutoGameModeEnabled"),
            process_name: None,
            expected_value: Some("0"),
            laptop_only: false,
        },
        LibraryCheck {
            id: "hw_gpu_scheduling",
            name: "Hardware GPU Scheduling",
            category: "Windows Gaming Features",
            description: "Required for benchmarks (GamersNexus). Reduces latency.",
            check_type: CheckType::RegistryDword,
            registry_path: Some("HKLM\\SYSTEM\\CurrentControlSet\\Control\\GraphicsDrivers"),
            registry_key: Some("HwSchMode"),
            process_name: None,
            expected_value: Some("2"),
            laptop_only: false,
        },
        LibraryCheck {
            id: "xbox_dvr_disabled",
            name: "Xbox Game DVR Disabled",
            category: "Windows Gaming Features",
            description: "Disables background recording which impacts performance",
            check_type: CheckType::RegistryDword,
            registry_path: Some("HKCU\\System\\GameConfigStore"),
            registry_key: Some("GameDVR_Enabled"),
            process_name: None,
            expected_value: Some("0"),
            laptop_only: false,
        },
        LibraryCheck {
            id: "background_apps_disabled",
            name: "Background Apps Disabled",
            category: "Windows Gaming Features",
            description: "Prevents UWP apps from running in background",
            check_type: CheckType::RegistryDword,
            registry_path: Some("HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\BackgroundAccessApplications"),
            registry_key: Some("GlobalUserDisabled"),
            process_name: None,
            expected_value: Some("1"),
            laptop_only: false,
        },
        LibraryCheck {
            id: "visual_effects_performance",
            name: "Visual Effects (Performance)",
            category: "Windows Gaming Features",
            description: "Disables Windows animations and effects",
            check_type: CheckType::RegistryDword,
            registry_path: Some("HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\VisualEffects"),
            registry_key: Some("VisualFXSetting"),
            process_name: None,
            expected_value: Some("2"),
            laptop_only: false,
        },

        // ===== Performance Registry Tweaks =====
        LibraryCheck {
            id: "network_throttling_disabled",
            name: "Network Throttling Disabled",
            category: "Performance Registry Tweaks",
            description: "Disables network throttling for max throughput (Back2Gaming)",
            check_type: CheckType::RegistryDword,
            registry_path: Some("HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile"),
            registry_key: Some("NetworkThrottlingIndex"),
            process_name: None,
            expected_value: Some("4294967295"), // 0xFFFFFFFF
            laptop_only: false,
        },
        LibraryCheck {
            id: "mmcss_gaming",
            name: "MMCSS System Responsiveness",
            category: "Performance Registry Tweaks",
            description: "Set to 0 for pure gaming/streaming (Back2Gaming)",
            check_type: CheckType::RegistryDword,
            registry_path: Some("HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile"),
            registry_key: Some("SystemResponsiveness"),
            process_name: None,
            expected_value: Some("0"),
            laptop_only: false,
        },
        LibraryCheck {
            id: "gpu_priority",
            name: "GPU Priority Boost",
            category: "Performance Registry Tweaks",
            description: "Increases GPU priority for games (Back2Gaming)",
            check_type: CheckType::RegistryDword,
            registry_path: Some("HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games"),
            registry_key: Some("GPU Priority"),
            process_name: None,
            expected_value: Some("8"),
            laptop_only: false,
        },

        // ===== Background Apps (Process Absent) =====
        LibraryCheck {
            id: "no_discord",
            name: "Discord Not Running",
            category: "Background Apps",
            description: "Discord uses significant CPU/GPU resources",
            check_type: CheckType::ProcessAbsent,
            registry_path: None,
            registry_key: None,
            process_name: Some("Discord.exe"),
            expected_value: None,
            laptop_only: false,
        },
        LibraryCheck {
            id: "no_chrome",
            name: "Chrome Not Running",
            category: "Background Apps",
            description: "Chrome is a major resource hog (Tom's Hardware)",
            check_type: CheckType::ProcessAbsent,
            registry_path: None,
            registry_key: None,
            process_name: Some("chrome.exe"),
            expected_value: None,
            laptop_only: false,
        },
        LibraryCheck {
            id: "no_firefox",
            name: "Firefox Not Running",
            category: "Background Apps",
            description: "Close browsers before benchmarking",
            check_type: CheckType::ProcessAbsent,
            registry_path: None,
            registry_key: None,
            process_name: Some("firefox.exe"),
            expected_value: None,
            laptop_only: false,
        },
        LibraryCheck {
            id: "no_edge",
            name: "Edge Not Running",
            category: "Background Apps",
            description: "Close browsers before benchmarking",
            check_type: CheckType::ProcessAbsent,
            registry_path: None,
            registry_key: None,
            process_name: Some("msedge.exe"),
            expected_value: None,
            laptop_only: false,
        },
        LibraryCheck {
            id: "no_spotify",
            name: "Spotify Not Running",
            category: "Background Apps",
            description: "Music streaming uses CPU and network",
            check_type: CheckType::ProcessAbsent,
            registry_path: None,
            registry_key: None,
            process_name: Some("Spotify.exe"),
            expected_value: None,
            laptop_only: false,
        },
        LibraryCheck {
            id: "no_teams",
            name: "Teams Not Running",
            category: "Background Apps",
            description: "Teams is resource-intensive",
            check_type: CheckType::ProcessAbsent,
            registry_path: None,
            registry_key: None,
            process_name: Some("ms-teams.exe"),
            expected_value: None,
            laptop_only: false,
        },
        LibraryCheck {
            id: "no_slack",
            name: "Slack Not Running",
            category: "Background Apps",
            description: "Slack uses significant resources",
            check_type: CheckType::ProcessAbsent,
            registry_path: None,
            registry_key: None,
            process_name: Some("slack.exe"),
            expected_value: None,
            laptop_only: false,
        },
        LibraryCheck {
            id: "no_obs",
            name: "OBS Not Running",
            category: "Background Apps",
            description: "OBS encoding impacts GPU performance",
            check_type: CheckType::ProcessAbsent,
            registry_path: None,
            registry_key: None,
            process_name: Some("obs64.exe"),
            expected_value: None,
            laptop_only: false,
        },
        LibraryCheck {
            id: "no_wallpaper_engine",
            name: "Wallpaper Engine Off",
            category: "Background Apps",
            description: "Animated wallpapers use GPU resources",
            check_type: CheckType::ProcessAbsent,
            registry_path: None,
            registry_key: None,
            process_name: Some("wallpaper64.exe"),
            expected_value: None,
            laptop_only: false,
        },
        LibraryCheck {
            id: "no_steam",
            name: "Steam Not Running",
            category: "Background Apps",
            description: "Steam client and overlay can impact benchmarks",
            check_type: CheckType::ProcessAbsent,
            registry_path: None,
            registry_key: None,
            process_name: Some("steam.exe"),
            expected_value: None,
            laptop_only: false,
        },
        LibraryCheck {
            id: "no_epic",
            name: "Epic Games Not Running",
            category: "Background Apps",
            description: "Epic launcher runs background services",
            check_type: CheckType::ProcessAbsent,
            registry_path: None,
            registry_key: None,
            process_name: Some("EpicGamesLauncher.exe"),
            expected_value: None,
            laptop_only: false,
        },
        LibraryCheck {
            id: "no_gog",
            name: "GOG Galaxy Not Running",
            category: "Background Apps",
            description: "GOG Galaxy client",
            check_type: CheckType::ProcessAbsent,
            registry_path: None,
            registry_key: None,
            process_name: Some("GalaxyClient.exe"),
            expected_value: None,
            laptop_only: false,
        },
        LibraryCheck {
            id: "no_onedrive",
            name: "OneDrive Not Running",
            category: "Background Apps",
            description: "OneDrive sync can impact disk I/O",
            check_type: CheckType::ProcessAbsent,
            registry_path: None,
            registry_key: None,
            process_name: Some("OneDrive.exe"),
            expected_value: None,
            laptop_only: false,
        },
        LibraryCheck {
            id: "no_dropbox",
            name: "Dropbox Not Running",
            category: "Background Apps",
            description: "Dropbox sync can impact disk I/O",
            check_type: CheckType::ProcessAbsent,
            registry_path: None,
            registry_key: None,
            process_name: Some("Dropbox.exe"),
            expected_value: None,
            laptop_only: false,
        },

        // ===== RGB/Peripheral Software =====
        LibraryCheck {
            id: "no_razer_synapse",
            name: "Razer Synapse Off",
            category: "RGB/Peripheral Software",
            description: "Razer software is known to cause performance issues",
            check_type: CheckType::ProcessAbsent,
            registry_path: None,
            registry_key: None,
            process_name: Some("Razer Synapse 3.exe"),
            expected_value: None,
            laptop_only: false,
        },
        LibraryCheck {
            id: "no_icue",
            name: "iCUE Not Running",
            category: "RGB/Peripheral Software",
            description: "Corsair iCUE can impact CPU usage",
            check_type: CheckType::ProcessAbsent,
            registry_path: None,
            registry_key: None,
            process_name: Some("iCUE.exe"),
            expected_value: None,
            laptop_only: false,
        },
        LibraryCheck {
            id: "no_armory_crate",
            name: "Armory Crate Off",
            category: "RGB/Peripheral Software",
            description: "ASUS Armory Crate background services",
            check_type: CheckType::ProcessAbsent,
            registry_path: None,
            registry_key: None,
            process_name: Some("ArmouryCrate.UserSessionHelper.exe"),
            expected_value: None,
            laptop_only: false,
        },
        LibraryCheck {
            id: "no_nzxt_cam",
            name: "NZXT CAM Off",
            category: "RGB/Peripheral Software",
            description: "NZXT CAM monitoring software",
            check_type: CheckType::ProcessAbsent,
            registry_path: None,
            registry_key: None,
            process_name: Some("NZXT CAM.exe"),
            expected_value: None,
            laptop_only: false,
        },
        LibraryCheck {
            id: "no_signalrgb",
            name: "SignalRGB Off",
            category: "RGB/Peripheral Software",
            description: "RGB control software",
            check_type: CheckType::ProcessAbsent,
            registry_path: None,
            registry_key: None,
            process_name: Some("SignalRgb.exe"),
            expected_value: None,
            laptop_only: false,
        },
        LibraryCheck {
            id: "no_lghub",
            name: "Logitech G Hub Off",
            category: "RGB/Peripheral Software",
            description: "Logitech gaming software",
            check_type: CheckType::ProcessAbsent,
            registry_path: None,
            registry_key: None,
            process_name: Some("lghub.exe"),
            expected_value: None,
            laptop_only: false,
        },
        LibraryCheck {
            id: "no_steelseries",
            name: "SteelSeries GG Off",
            category: "RGB/Peripheral Software",
            description: "SteelSeries software",
            check_type: CheckType::ProcessAbsent,
            registry_path: None,
            registry_key: None,
            process_name: Some("SteelSeriesGG.exe"),
            expected_value: None,
            laptop_only: false,
        },

        // ===== Monitoring Software (Process Present) =====
        LibraryCheck {
            id: "afterburner_running",
            name: "MSI Afterburner Running",
            category: "Monitoring Software",
            description: "Required for GPU monitoring during benchmarks",
            check_type: CheckType::ProcessPresent,
            registry_path: None,
            registry_key: None,
            process_name: Some("MSIAfterburner.exe"),
            expected_value: None,
            laptop_only: false,
        },
        LibraryCheck {
            id: "hwinfo_running",
            name: "HWiNFO Running",
            category: "Monitoring Software",
            description: "Detailed hardware monitoring",
            check_type: CheckType::ProcessPresent,
            registry_path: None,
            registry_key: None,
            process_name: Some("HWiNFO64.exe"),
            expected_value: None,
            laptop_only: false,
        },
        LibraryCheck {
            id: "obs_running",
            name: "OBS Studio Running",
            category: "Monitoring Software",
            description: "For streaming/recording scenarios",
            check_type: CheckType::ProcessPresent,
            registry_path: None,
            registry_key: None,
            process_name: Some("obs64.exe"),
            expected_value: None,
            laptop_only: false,
        },
        LibraryCheck {
            id: "steamvr_running",
            name: "SteamVR Running",
            category: "Monitoring Software",
            description: "Required for VR benchmarking",
            check_type: CheckType::ProcessPresent,
            registry_path: None,
            registry_key: None,
            process_name: Some("vrserver.exe"),
            expected_value: None,
            laptop_only: false,
        },

        // ===== Laptop-Specific =====
        LibraryCheck {
            id: "nvidia_battery_boost_off",
            name: "NVIDIA Battery Boost Off",
            category: "Laptop-Specific",
            description: "Battery Boost caps FPS to 30. Disable for benchmarks.",
            check_type: CheckType::RegistryDword,
            registry_path: Some("HKCU\\Software\\NVIDIA Corporation\\Global\\Battery Boost"),
            registry_key: Some("EnableBatteryBoost"),
            process_name: None,
            expected_value: Some("0"),
            laptop_only: true,
        },
        LibraryCheck {
            id: "nvidia_whisper_mode_off",
            name: "NVIDIA Whisper Mode Off",
            category: "Laptop-Specific",
            description: "Whisper Mode limits performance for quieter operation",
            check_type: CheckType::RegistryDword,
            registry_path: Some("HKCU\\Software\\NVIDIA Corporation\\Global\\Whisper Mode"),
            registry_key: Some("EnableWhisperMode"),
            process_name: None,
            expected_value: Some("0"),
            laptop_only: true,
        },
    ]
}

/// Get checks filtered by category
#[allow(dead_code)]
pub fn get_checks_by_category(category: &str) -> Vec<LibraryCheck> {
    get_library()
        .into_iter()
        .filter(|c| c.category == category)
        .collect()
}
